server:
  port: 8081
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  redis:
    host: 10.1.10.84
    port: 6379
    password: LL159753
    database: 0
    # 连接超时时间
    timeout: 5000
    lettuce:
      pool:
        max-active: 512   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 50     #最大等待连接中的数量,设 0 为没有限制
        max-wait: 5000    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制